name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
        # run: |
        #   sudo apt-get update
        #   sudo apt-get install jq
        #   jq 'del(.devDependencies["loki"])' package.json > temp_package.json
        #   mv package.json original_package.json
        #   mv temp_package.json package.json
        #   npm install
        #   mv original_package.json package.json
        #   npm install -D loki --force
      - name: Build production project
        run: npm run build:prod
        if: always()
      - name: Linting typescript
        run: npm run lint:ts
        if: always()
      - name: Linting css
        run: npm run lint:scss
        if: always()
      - name: Unit testing
        run: npm run test:unit
        if: always()
      # - name: build storybook
      #   run: npm run storybook:build
      # - name: screenshot testing
      #   run: npm run test:ui:ci

