name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules 1
        run: sudo apt-get update
      - name: install modules 2
        run: sudo apt-get install jq
      - name: install modules 3
        run: jq 'del(.dependencies["loki"])' package.json > temp_package.json
      - name: install modules 4  
        run: mv package.json original_package.json
      - name: install modules 5
        run: mv temp_package.json package.json
      - name: install modules 6
        run: npm install
      - name: install modules 7
        run: mv original_package.json package.json
      - name: install modules 8
        run: npm install loki --force
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
